
####
#### Container Setup Group
####

dockerSetupPanel:
    kind: panel
    name: dockerSetupPanel
    label: Docker Server Setup
    contents:
        containerHostTable:
            tag: "div#container-host-manager"
        csStylesheet:
        #   tag: link|rel="stylesheet"|type="text/css"|href="/scripts/xnat/plugin/containerService/containerConfig.css"
            tag: link|rel="stylesheet"|type="text/css"|href="~/scripts/xnat/plugin/containerService/containerConfig.css"
        csHistoryScript:
#           tag: script|src="/scripts/xnat/plugin/containerService/containerService-history.js"
            tag: script|src="~/scripts/xnat/plugin/containerService/containerService-history.js"
        csSiteAdminScripts:
#           tag: script|src="/scripts/xnat/plugin/containerService/containerService-siteAdmin.js"
            tag: script|src="~/scripts/xnat/plugin/containerService/containerService-siteAdmin.js"

imageHostsPanel:
    kind: panel
    name: imageHosts
    label: Image Hosts
    contents:
        imageHostTemplate:
            tag: "div#image-host-editor-template.html-template"
            contents:
                imageHostEditor:
                    kind: panel.form
                    name: imageHostEditor
                    id: image-host-editor
                    header: false
                    footer: false
                    action: /xapi/docker/hubs
                    contentType: json
                    element:
                        style:
                            padding: 20px 0
                    contents:
                        name:
                            kind: panel.input.text
                            id: hub-name
                            name: name
                            label: Image Host Name
                            validation: not-empty
                        url:
                            kind: panel.input.text
                            id: hub-url
                            name: url
                            label: URL
                            validation: url not-empty
        imageHostTable:
            tag: "div#image-host-manager"

installedImagesPanel:
    kind: panel
    name: installedImagesPanel
    label: Installed Container Images and Commands
    contents:
        imageFilterBar:
            tag: "div#image-filter-bar"
        imageListContainer:
            tag: "div#image-list-container"
        addImageTemplate:
            tag: "div#add-image-template.html-template"
            contents:
                addImageform:
                    kind: panel.form
                    id: add-image-form
                    header: false
                    footer: false
                    element:
                        style:
                            padding: 20px 0
                    contents:
                        hubId:
                            kind: panel.select.single
                            name: hubId
                            label: Select Image Host
                            element:
                                title: Select Image Host
                        image:
                            kind: panel.input.text
                            name: image
                            label: Image Name
                            validation: not-empty
                            element:
                                title: Enter Image Name
                            description: >
                                Specify the image name to pull, including the account name (if necessary). For example, to pull the XNAT dcm2niix image, enter "xnat/dcm2niix"
                        tagInput:
                            kind: panel.input.text
                            name: tag
                            label: Version Tag
                            value: ":latest"
                            element:
                                title: Enter Version Tag (Optional)
                            description: >
                                "Specify the tag version of the image to pull. The default is :latest"
                        saveCommands:
                            kind: panel.input.hidden
                            name: save-commands
                            value: true
        setCommandDefaults:
            tag: "div#set-command-defaults-template.html-template"
            contents:
                setCommandDefaultForm:
                    kind: panel
                    name: setCommandDefaultsForm
                    id: set-command-defaults-form
                    header: false
                    footer: false
                    element:
                        style:
                            padding: 20px 0
                    contents:
                        imageId:
                            kind: panel.input.hidden
                            name: imageId
                        commandId:
                            kind: panel.input.hidden
                            name: commandId
        commandViewerTemplate:
            tag: "div#command-viewer-template.html-template"
            contents:
                commandViewer:
                    kind: panel
                    name: commandViewer
                    id: command-viewer
                    header: false
                    footer: false
                    element:
                        style:
                            padding: 20px 0
                    contents:
                        commandViewerDisplay:
                            tag: textarea.commandViewer

sitewideCommandConfigsPanel:
    kind: panel
    name: sitewideCommandConfigsPanel
    label: Site-wide Command Configurations
    footer: false
    contents:
        commandConfigDescription:
            tag: div.message
            contents:
                "This panel lists all commands and XNAT-aware command wrappers from all installed images, and allows admins to define a site-wide configuration for each command wrapper. This site-wide configuration can be used by default by a project, or a project can create its own configuration to overwrite the site-wide defaults."
        commandConfigListContainer:
            tag: "div#command-config-list-container"
        commandConfigTemplate:
            tag: "div#command-config-template.html-template"
            contents:
                configViewer:
                    kind: panel
                    name: configViewer
                    id: config-viewer
                    header: false
                    footer: false

siteCommandAutomationPanel:
    kind: panel
    name: siteCommandAutomationPanel
    label: Command Automation
    contents:
        siteCommandAutomationNote:
            tag: div.message
            contents:
                "With this panel, you can set up an automated command execution that will be triggered by an XNAT event, such as an image session being archived."
        siteCommandAutomationTable:
            tag: div#command-automation-admin-list
            contents: Table will go here

sitewideCommandHistoryPanel:
    kind: panel
    name: sitewideCommandHistoryPanel
    label: Site-wide Container Execution Log
    footer: false
    contents:
        commandHistoryTableContainer:
            tag: div#command-history-container
            contents: Loading history entries...

#################################################
####  Root Site Admin Spawner Config Object  ####
#################################################

siteSettings:
    kind: tabs
    name: containerAdminPage
    label: Administer Container Service
    meta:
        tabGroups:
            containerServiceTabGroup: Container Service
    contains: tabs
    tabs:
        containerServicesTab:
            kind: tab
            name: containerSetupTab
            label: Container Server Setup
            group: containerServiceTabGroup
            active: true
            contents:
                ${dockerSetupPanel}
                ${imageHostsPanel}
        imageCommandTab:
            kind: tab
            name: imagesCommandsTab
            label: "Images & Commands"
            group: containerServiceTabGroup
            active: false
            contents:
                ${installedImagesPanel}
        commandConfigTab:
            kind: tab
            name: commandConfigTab
            label: Command Configurations
            group: containerServiceTabGroup
            active: false
            contents:
                ${sitewideCommandConfigsPanel}
        commandAutomationAdminTab:
            kind: tab
            name: commandAutomationAdminTab
            label: Command Automation
            group: containerServiceTabGroup
            active: false
            contents:
                ${siteCommandAutomationPanel}
        commandHistoryTab:
            kind: tab
            name: commandHistoryTab
            label: Command History
            group: containerServiceTabGroup
            active: false
            contents:
                ${sitewideCommandHistoryPanel}

